spring:
  cache:
    type: hazelcast

  session:
    store-type: hazelcast

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: demo
      hibernate.cache.hazelcast.shutdown_on_session_factory_close: false

  h2:
    console:
      enabled: true

security:
  user:
    password: password
